DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
  id IDENTITY PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email VARCHAR(255) NOT NULL,
  birth_date DATE
);

CREATE TABLE post(
  id IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content VARCHAR NOT NULL,
  time SMALLDATETIME AS CURRENT_TIMESTAMP NOT NULL,
  rate INT DEFAULT 0);


